client_config_backend: settings
client_config:
    client_id: 578330744081-02kbhmjl1s2p6t8dln9o62rl35te5o25.apps.googleusercontent.com
    client_secret: 4UyAdiNUwpoYrvgofNmkE2fH


save_credentials: True
save_credentials_backend: file
save_credentials_file: settings/credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install
